# SEO Tags 
title: "Amanda Desire Evelyn"
tagline: "Florals with Feeling"
description: "Botanical artist and face painter based in the pacific northwest"
logo: "/assets/images/logo.png"
lang: "en_US"
url: "http://byamanda.design"
google_site_verification: "5lWzIeJxNMYNGZ_DIfeq15ZqI28HkII9cFXCSAAWld8"

# Global Variables
social:
  # These are used for the jekyll build
  name: "Amanda Desiree Hamill"
  instagram: "http://instagram.com/floralsbyamanda"
  email: "desireeevelynart@gmail.com"
  facebook: "http://www.facebook.com/amandadesireeevelyn"
  youtube: "https://www.youtube.com/channel/UCvBizVmlOTlE87GTnSAtPUw"

  # Meta tags
  links:
    - "http://instagram.com/floralsbyamanda"
    - "desireeevelynart@gmail.com"
    - "http://www.facebook.com/amandadesireeevelyn"
    - "https://www.youtube.com/channel/UCvBizVmlOTlE87GTnSAtPUw"

collections:
  events:
    output: true

defaults:
  - scope: 
      path: ""
      type: "events"
    values:
      layout: "event"
      page_id: "event"
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
