# SEO Tags 
title: "Amanda Desire Evelyn"
tagline: "Florals with Feeling"
description: "Botanical artist and face painter based in the pacific northwest"
logo: "/assets/images/logo.png"
lang: "en_US"
url: "https://byamanda.design"
google_site_verification: "5lWzIeJxNMYNGZ_DIfeq15ZqI28HkII9cFXCSAAWld8"

# Global Variables
social:
  links:
    - "http://instagram.com/floralsbyamanda"
    - "desireeevelynart@gmail.com"
    - "http://www.facebook.com/amandadesireeevelyn"
    - "https://www.youtube.com/channel/UCvBizVmlOTlE87GTnSAtPUw"

collections:
  events:
    output: true
  gallery:
    output: false

defaults:
  - scope: 
      path: ""
      type: "events"
    values:
      layout: "event"
      page_id: "event"
  - scope: 
      path: ""
      type: "gallery"
    values:
      page_id: "gallery"
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
